// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://occmlmdgjrbaesgwprec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jY21sbWRnanJiYWVzZ3dwcmVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDEyMjUsImV4cCI6MjA3MjU3NzIyNX0.o_dBFY7RuiRUYkxH6OBSoV-V98qKf0BiDWM3PJjsems";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});