// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvrujtmziyibvuyhooyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cnVqdG16aXlpYnZ1eWhvb3lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MTY3MjIsImV4cCI6MjA3NDk5MjcyMn0.cNFAF0adAHjbUYrOTz4l4xddmu5PYrNfAh0i_RgQ4SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});